### PR TITLE
allow multiple paths per script

### PR DESCRIPTION
**Pull request by ryanpineo**
added a new `paths` variable that can be used in each script instead of `path` to allow people to specify multiple paths in 1 script without breaking backwards compatibility.

### CODE REVIEW

**Comment by otakup0pe** [comment]
This seems to work for me. A test would be cool tho.

**Comment by colin-nolan** [comment]
This pull request a duplicate of https://github.com/nickhammond/ansible-logrotate/pull/17, albeit that it doesn't overload the `path` property (a new `paths` property is defined instead).

@nickhammond: It would be great if one of these requests was merged :).

**Comment by nickhammond** [comment]
Planning on merging in this one, just need to add a test for it as @otakup0pe mentioned.

**Comment by ryanpineo** [comment]
@nickhammond I tried adding a test, let me know if it's good

**Comment by nickhammond** [comment]
@ryanpineo this looks great, I'll get this merged in this weekend and then bump the version. Thanks for keeping backwards compatibility as well!

**Comment by nickhammond** [comment]
Merged and tagged as v0.0.5, thanks!

**Pull request merged**
